name: iOS Github Action CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: pod
        run: pod install

      - name: Xcode Version
        run: /usr/bin/xcodebuild -version
      
      - name: Xcode build iOS App
      - run: |
         xcodebuild clean build -scheme App -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0'
